before:
  hooks:
#    - mkdir -p build
#    - cp main.go build/main.go
#    - cp ./go.mod build/go.mod
    # GoReleaser doesn't seem to offer {{.Tag}} at this stage, so we have to embed it into the env
    # so we run: TAG=$(git describe --abbrev=0) goreleaser release --rm-dist --skip-publish --skip-validate
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: main.go
    dir: .
    binary: httpget
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: mac
checksum:
  algorithm: sha512
release:
  github:
    owner: colachg
    name: http-over-socks
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs?:'
      - '^tests?:'
      - '^\w+\s+' # a hack to remove commit messages without colons thus don't correspond to a package